### ISSUE TITLE
Provide a smoother experience for iOS installs

### ISSUE THREAD

**Issue by philschatz** [philschatz/puzzlescript#149]
See https://www.netguru.com/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native

![image](https://user-images.githubusercontent.com/253202/54331164-a4220b80-45e6-11e9-9cfa-1528e39a9ea4.png)

specifically, something like this to make the popup point to the button in safari:

```css
.popup-pointer {
    display: block;
    position: absolute;
    content: "";
    width: 10px;
    height: 10px;
    right: -10px;
    bottom: 10px;
    background-color: inherit;
    transform: translateX(-6px) rotate(45deg);
    pointer-events: none;
}
```
